### PR TITLE
[WIP] Support for DEFINEs and other fixes

### PR DESCRIPTION
**Pull request by rsbeckerca**
Fixes: #28
Fixes: #45
Fixes: #46

Signed-off-by: Randall S. Becker <rsbecker@nexbridge.com>

### CODE REVIEW

**Comment by rsbeckerca** [comment]
Add DEFINE support. I would rather take all of the 4.3 changes instead of the mix and match for this PR.

**Review by Jojo-Schmitz — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
Why those CodeQL errors?

**Comment by rsbeckerca** [comment]
I'm going to look later. Still want to go to 4.3

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rsbeckerca** [comment]
4.3 code base is now in place. Builds in NSDEE. Am working on CodeQL and OSS

**Comment by rsbeckerca** [comment]
Regression test passes for this fix. I have a Jenkinsfile update coming so that the tests will be run.

**Review by Jojo-Schmitz — APPROVED** [review]

**Review by Jojo-Schmitz — APPROVED** [review]

**Pull request merged**
