### PR TITLE
Add extensions to tandem_ext.c for $(wildcard)

### PR DESCRIPTION
**Pull request by rsbeckerca**
Add extensions to tandem_ext.c for $(wildcard),

This includes handling a ./ prefix and . alone passed to stat(). Processing
for patterns is done by converting Guardian into OSS and reading the OSS
directory to perform pattern matching. The matched names are then converted
back to Guardian for use by the makefile. Conversion methods are added to
tandem_ext.c.

stat() is made aware of this and handles OSS names. Directories and sub-volumes
passed to stat() are simulated and do not contain actual information.

The manual has also been updated to document $(wildcard) behaviour.

Unit test t0001 added to test conversion methods.

Removed RCS and SCCS support because if incompatibilities with this change.

Fixes: #102

### CODE REVIEW

**Comment by rsbeckerca** [comment]
This is a work in progress. Not ready for review or anything but comments appreciated.

**Comment by rsbeckerca** [comment]
Now ready for review.

**Review by Jojo-Schmitz — APPROVED** [review]
I don't claim to understand every single change, but as far as I can tell it looks fine

**Comment by rsbeckerca** [comment]
> I don't claim to understand every single change, but as far as I can tell it looks fine

Thanks @Jojo-Schmitz. Maybe we can get @xidbhonaker and @the4amfriend to have a look also. This was basically incremental test fixes until it worked, but I'm not 100% sure about the changes.

**Comment by xidbhonaker** [comment]
Randall,

I looked at all the changes in tandem_ext.c and have a fair understanding of your strategy.  That strategy looks sound, and I have to assume you've done some testing to validate that the code works as expected.  I though I needed to approve (but it already looks like it has).  I know this was a tough one... kudos for fighting it.

**Comment by rsbeckerca** [comment]
> Randall,
> 
> I looked at all the changes in tandem_ext.c and have a fair understanding of your strategy. That strategy looks sound, and I have to assume you've done some testing to validate that the code works as expected. I though I needed to approve (but it already looks like it has). I know this was a tough one... kudos for fighting it.

Thanks Bill. I've tested it. Would rather have some unit test capability on `tandem_ext.c`

**Comment by the4amfriend** [comment]
I'm not sure if this is relevant but are there checks in place for any OSS filename that get passed through? Just being cautious that OSS filenames can contain periods (.) as well. Otherwise, changes look good to me. Well done!

**Comment by rsbeckerca** [comment]
> I'm not sure if this is relevant but are there checks in place for any OSS filename that get passed through? Just being cautious that OSS filenames can contain periods (.) as well. Otherwise, changes look good to me. Well done!

Well... the file names are supposed to be valid and Guardian. OSS names cannot be passed in unless they are `/G` or `/E`. The `toGuardian` takes an OSS-form of a Guardian name, while `toOss` takes a Guardian name and converts to OSS so `opendir()` can be called. Not sure there is a case where a `.` can slip through.

**Comment by rsbeckerca** [comment]
Based on comments from @the4amfriend, I am putting this back to WIP and setting up unit tests so the `toOss` and `toGuardian` methods can be tested. Other tests may come also.

**Comment by rsbeckerca** [comment]
I have updated gmake with unit tests for conversion of paths/files to/from Guardian/OSS based on comments from @the4amfriend. This was a good thing.  A bunch of defects in the conversion were found and fixed.

**Comment by rsbeckerca** [comment]
I found an issue with wildcard not always resolving things. Moved back to draft.

**Comment by rsbeckerca** [comment]
A side-effect appears to be introduced when using `$(wildcard)`. GMake seems to want to use the `RCS` directory to find the makefile. This is wrong. It may be a GMake 4.3 bug but needs to be resolved.

**Comment by rsbeckerca** [comment]
Found the problem. It was because implicit RCS and SCCS rules were being incorrectly invoked. They are inappropriate for Guardian.

**Review by Jojo-Schmitz — APPROVED** [review]
Looks good to me!

**Pull request merged**
