### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by rsbeckerca**
Add pull request template for the gmake project.

CLA: Full use of this content is made available with permission to the ITUGLIB team.

Signed-off-by: Randall S. Becker <rsbecker@nexbridge.com>

### CODE REVIEW

**Comment by rsbeckerca** [comment]
Once we get a draft CLA in PDF form, we can put it in `policies/ituglib_cla.pdf` and will be referenced by the contents of this PR.

**Comment by xidbhonaker** [comment]
You made a statement "However, the owners reserve the exclusive and arbitrary right to decide that your contribution is not trivial without debate or recourse."  May need clarification on 'owners'; is it GNUMake (owners of the software) or ITUGLIB (owners of the repo).

Fine with the rest.

**Comment by rsbeckerca** [comment]
> 
> 
> You made a statement "However, the owners reserve the exclusive and arbitrary right to decide that your contribution is not trivial without debate or recourse." May need clarification on 'owners'; is it GNUMake (owners of the software) or ITUGLIB (owners of the repo).
> 
> Fine with the rest.

Instead of saying "You made the statement", please open the commit, click on the line, and add a comment. It makes code receives much easier than searching for what you might mean. Thanks.

**Comment by rsbeckerca** [comment]
> 
> 
> > You made a statement "However, the owners reserve the exclusive and arbitrary right to decide that your contribution is not trivial without debate or recourse." May need clarification on 'owners'; is it GNUMake (owners of the software) or ITUGLIB (owners of the repo).
> > Fine with the rest.
> 
> Instead of saying "You made the statement", please open the commit, click on the line, and add a comment. It makes code receives much easier than searching for what you might mean. Thanks.

@xidbhonaker Changes clarified per your request. Awaiting new review approval.

**Comment by xidbhonaker** [comment]
I haven’t had time to sync the project here yet.  Busy working with a customer.  If this can wait a few days I can get to it.  Sorry…

Bill

**Review by xidbhonaker — APPROVED** [review]
Looks good to me.

**Comment by rsbeckerca** [comment]
> 
> 
> Looks good to me.

Thanks.

**Pull request merged**
