### PR TITLE
Move cleanWs() to success{} section.

### LINKED ISSUE #64: [Bug] Jenkinsfile should leave content if builds fail
The build script should leave the clone around for diagnostics.

### PR DESCRIPTION
**Pull request by rsbeckerca**
Fixes #64

Signed-off-by: Randall S. Becker <rsbecker@nexbridge.com>

### CODE REVIEW

**Review by Jojo-Schmitz — APPROVED** [review]

**Comment by rsbeckerca** [comment]
Please approve ASAP

**Comment by rsbeckerca** [comment]
Well, GitHub is sure taking its time.

**Comment by Jojo-Schmitz** [comment]
Looks like it got stuck?

**Comment by rsbeckerca** [comment]
I'm not sure what to do about it

**Pull request merged**
