### PR TITLE
Modified ar_name_equal to support case-insensitivity.

### LINKED ISSUE #1: Archives are not correctly functioning because of case insensitivity.
The AR utility stores object file names in upper case. This is not taken into account by the gmake code.

### PR DESCRIPTION
**Pull request by rsbeckerca**
CLA: trivial
Fixes #1.

Signed-off-by: Randall S. Becker <randall.becker@nexbridge.ca>

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Seems the PR messages is not related at all to any of the commits?
Also the check(s) fail on them?
And there't there's a merge conflict.

**Review by Jojo-Schmitz — COMMENTED** [review]
Looks good to me

**Comment by Jojo-Schmitz** [comment]
Ooops, I didn't intend to close it!

**Comment by rsbeckerca** [comment]
Can you reopen?

**Comment by Jojo-Schmitz** [comment]
The field/button is disabled.

**Comment by rsbeckerca** [comment]
I have to recreate it.

**Comment by Jojo-Schmitz** [comment]
Sorry, seems I fat-fingered and use the wrong button...

**Pull request closed without merging**
