### PR TITLE
Define platform specific variables.

### PR DESCRIPTION
**Pull request by rsbeckerca**
* Remove NMC from L-series builds.
* Add TNS_PLATFORM (E/X values only).
* Add TOS_VERSION support

Fixes: #74

Signed-off-by: Randall S. Becker <rsbecker@nexbridge.com>

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Why not R and V too?

**Comment by rsbeckerca** [comment]
> 
> 
> Why not R and V too?

We don’t build `GMAKE` for `R` and there is no build difference between `X` and `V`. Is there? I do not think there is a _TNS_V_TARGET as of yet.

**Review by Jojo-Schmitz — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
True.

**Comment by rsbeckerca** [comment]
Going to wait for comments from @xidbhonaker in case he has other requirements from his `GMAKE` use cases.

**Comment by xidbhonaker** [comment]
You should go ahead.  Small chance of me finding anything and today is pretty busy.

**Comment by rsbeckerca** [comment]
This will go as version `4.3g2` once approved

**Review by Jojo-Schmitz — APPROVED** [review]

**Pull request merged**
